[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ПВ"
authors = [{name = "VVKo", email = "v.kovdrysh@gmail.com"}]
dynamic = ["version", "description"]
