[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nat_dep_clg"
authors = [{name = "nat_dep_clg", email = "nat_dep_clg@chnu.edu.ua"}]
dynamic = ["version", "description"]
